# Generated by Django 3.2.15 on 2022-10-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_booking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
